//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("firstApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Always [ˈɔːlw(e)ɪz] всегда, неизменно, постоянно, вечно
        ///Animal [ˈænɪməl] животное
        ///Answer [ˈɑːnsə] ответ
        ///Anymore [enɪˈmɔː] больше, больше не
        ///Anything [ˈenɪθɪŋ] Что-нибудь
        ///Basement [ˈbeɪsmənt] подвал, цоколь, подвальное помещение
        ///Basketball [ˈbɑːskɪtbɔːl] баскетбол, баскетбольный мяч
        ///Because [bɪˈkɒz] потому что, поскольку, ведь
        ///Book [bʊk] книга, книжка
        ///Boy [bɔɪ] мальчик
        ///Braces [ˈbreɪsɪz] ортодонтические скобки, брекеты
        ///Breakfast [ˈbrekfəst] завтрак
        ///Car [kɑː] машина
        ///Careful [ˈkeəf(ə)l] осторожны [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always [ˈɔːlw(e)ɪz] всегда, неизменно, постоянно, вечно
        ///Animal [ˈænɪməl] животное
        ///Answer [ˈɑːnsə] ответ
        ///Anymore [enɪˈmɔː] больше, больше не
        ///Anything [ˈenɪθɪŋ] Что-нибудь
        ///Basement [ˈbeɪsmənt] подвал, цоколь, подвальное помещение
        ///Basketball [ˈbɑːskɪtbɔːl] баскетбол, баскетбольный мяч
        ///Because [bɪˈkɒz] потому что, поскольку, ведь
        ///Book [bʊk] книга, книжка
        ///Boy [bɔɪ] мальчик
        ///Braces [ˈbreɪsɪz] ортодонтические скобки, брекеты
        ///Breakfast [ˈbrekfəst] завтрак
        ///Car [kɑː] машина
        ///Careful [ˈkeəf(ə)l] осторожный, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NewWords {
            get {
                return ResourceManager.GetString("NewWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string OldWords {
            get {
                return ResourceManager.GetString("OldWords", resourceCulture);
            }
        }
    }
}
